language: python
python:
  - "3.7"
  - "3.8"
install:
  - pip install pipenv
script:
  - python setup.py install
  - cd docs  # Switch folder to avoid conflicts between ./sslyze and the installed sslyze module
  - python ../api_sample.py
  - pip uninstall -y sslyze
  - cd ..
  - pipenv install --dev
  - invoke test
