name: Run Tests

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pip
      run: |
        python -m pip install --upgrade pip pipenv setuptools

    - name: Test SSLyze module setup
      run: |
        python setup.py install
        cd docs  # Switch folder to avoid conflicts between ./sslyze and the installed sslyze module
        python ../api_sample.py
        cd ..
        pip uninstall -y sslyze

    - name: Install dev dependencies
      run: pipenv install --dev

    - name: Run linters
      # Only do linting once
      if: matrix.python-version == 3.7
      run: pipenv run invoke lint

    - name: Run tests
      run: pipenv run invoke test
